formofway:  A description of the road based on its nature or use
primaryrou: States if the RoadLink forms part of the Primary Route network
operationa:  Indicator identifying the construction status of the road
directiona: Indication of the direction of traffic flow.
startgrade: The relative level of the link at the startNode
endgradese: The relative level of the link at the endNode.
elevationg:  The elevation gain is calculated from three-dimensional geometry to define the total ascent 
experienced when passing along a RoadLink feature.

In [1]:
import geopandas as gpd
import pandas as pd

F:\Anaconda3\lib\site-packages\geopandas\_compat.py:124: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
<ipython-input-1-f94283bcb326>:1: DeprecationWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas still uses PyGEOS by default. However, starting with version 0.14, the default will switch to Shapely. To force to use Shapely 2.0 now, you can either uninstall PyGEOS or set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In the next release, GeoPandas will switch to using Shapely by default, even if PyGEOS is installed. If you only have PyGEOS installed to get speed-ups, this switch should be smooth. However, if you are using PyGEOS directly (calling PyGEOS func

In [2]:
big = pd.read_csv('wes_net_0827/data_preprocess/FeatureMatrix_wes.csv')
big

toid        date  car  \
0        osgb4000000030407372  2020/01/01   65   
1        osgb4000000030407372  2020/01/02   89   
2        osgb4000000030407372  2020/01/03   90   
3        osgb4000000030407372  2020/01/04   80   
4        osgb4000000030407372  2020/01/05   84   
...                       ...         ...  ...   
5640997  osgb4000000031063610  2021/12/27    0   
5640998  osgb4000000031063610  2021/12/28    0   
5640999  osgb4000000031063610  2021/12/29    0   
5641000  osgb4000000031063610  2021/12/30    7   
5641001  osgb4000000031063610  2021/12/31    1   

                                                  geometry    roadclassi  \
0                LINESTRING (528098 179231, 528124 179232)         BRoad   
1                LINESTRING (528098 179231, 528124 179232)         BRoad   
2                LINESTRING (528098 179231, 528124 179232)         BRoad   
3                LINESTRING (528098 179231, 528124 179232)         BRoad   
4                LINESTRING (528098 179231, 528124 179232)         BRoad   
...                                                    ...           ...   
5640997  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5640998  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5640999  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5641000  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5641001  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   

         length           formofway  trunkroad  primaryrou      directiona  \
0         26.01  Single Carriageway        0.0         0.0  bothDirections   
1         26.01  Single Carriageway        0.0         0.0  bothDirections   
2         26.01  Single Carriageway        0.0         0.0  bothDirections   
3         26.01  Single Carriageway        0.0         0.0  bothDirections   
4         26.01  Single Carriageway        0.0         0.0  bothDirections   
...         ...                 ...        ...         ...             ...   
5640997   22.79  Single Carriageway        0.0         0.0  bothDirections   
5640998   22.79  Single Carriageway        0.0         0.0  bothDirections   
5640999   22.79  Single Carriageway        0.0         0.0  bothDirections   
5641000   22.79  Single Carriageway        0.0         0.0  bothDirections   
5641001   22.79  Single Carriageway        0.0         0.0  bothDirections   

         startgrade  endgradese elevationg  Volume  
0               0.0         0.0         0m     NaN  
1               0.0         0.0         0m     NaN  
2               0.0         0.0         0m     NaN  
3               0.0         0.0         0m     NaN  
4               0.0         0.0         0m     NaN  
...             ...         ...        ...     ...  
5640997         0.0         0.0         0m     NaN  
5640998         0.0         0.0         0m     NaN  
5640999         0.0         0.0         0m     NaN  
5641000         0.0         0.0         0m     NaN  
5641001         0.0         0.0         0m     NaN  

[5641002 rows x 14 columns]

In [3]:
columns_to_check = ['roadclassi', 'formofway', 'primaryrou', 'directiona', 'startgrade', 'endgradese']

for column in columns_to_check:
    unique_values_counts = big[column].value_counts()
    print(f"Unique values and counts for '{column}':")
    print(unique_values_counts)

Unique values and counts for 'roadclassi':
Unclassified    3668328
ARoad           1293975
BRoad            342630
LocalRoad        336069
Name: roadclassi, dtype: int64
Unique values and counts for 'formofway':
Single Carriageway                 4271940
Traffic Island Link At Junction     542376
Dual Carriageway                    419904
Traffic Island Link                 194643
Roundabout                           65610
Slip Road                            59049
Enclosed Traffic Area                45927
Shared Use Carriageway               41553
Name: formofway, dtype: int64
Unique values and counts for 'primaryrou':
0.0    5217453
1.0     423549
Name: primaryrou, dtype: int64
Unique values and counts for 'directiona':
bothDirections         3179898
inDirection            1340631
inOppositeDirection    1120473
Name: directiona, dtype: int64
Unique values and counts for 'startgrade':
0.0    5599449
1.0      41553
Name: startgrade, dtype: int64
Unique values and counts for 'endgrades

In [4]:
big['elevationg'] = big['elevationg'].replace('m$', '', regex=True).astype(float)
big.rename(columns={'Volume': 'smalldata','car': 'bigdata'}, inplace=True)
big

toid        date  bigdata  \
0        osgb4000000030407372  2020/01/01       65   
1        osgb4000000030407372  2020/01/02       89   
2        osgb4000000030407372  2020/01/03       90   
3        osgb4000000030407372  2020/01/04       80   
4        osgb4000000030407372  2020/01/05       84   
...                       ...         ...      ...   
5640997  osgb4000000031063610  2021/12/27        0   
5640998  osgb4000000031063610  2021/12/28        0   
5640999  osgb4000000031063610  2021/12/29        0   
5641000  osgb4000000031063610  2021/12/30        7   
5641001  osgb4000000031063610  2021/12/31        1   

                                                  geometry    roadclassi  \
0                LINESTRING (528098 179231, 528124 179232)         BRoad   
1                LINESTRING (528098 179231, 528124 179232)         BRoad   
2                LINESTRING (528098 179231, 528124 179232)         BRoad   
3                LINESTRING (528098 179231, 528124 179232)         BRoad   
4                LINESTRING (528098 179231, 528124 179232)         BRoad   
...                                                    ...           ...   
5640997  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5640998  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5640999  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5641000  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   
5641001  LINESTRING (527536.5669999998 181725.814999999...  Unclassified   

         length           formofway  trunkroad  primaryrou      directiona  \
0         26.01  Single Carriageway        0.0         0.0  bothDirections   
1         26.01  Single Carriageway        0.0         0.0  bothDirections   
2         26.01  Single Carriageway        0.0         0.0  bothDirections   
3         26.01  Single Carriageway        0.0         0.0  bothDirections   
4         26.01  Single Carriageway        0.0         0.0  bothDirections   
...         ...                 ...        ...         ...             ...   
5640997   22.79  Single Carriageway        0.0         0.0  bothDirections   
5640998   22.79  Single Carriageway        0.0         0.0  bothDirections   
5640999   22.79  Single Carriageway        0.0         0.0  bothDirections   
5641000   22.79  Single Carriageway        0.0         0.0  bothDirections   
5641001   22.79  Single Carriageway        0.0         0.0  bothDirections   

         startgrade  endgradese  elevationg  smalldata  
0               0.0         0.0         0.0        NaN  
1               0.0         0.0         0.0        NaN  
2               0.0         0.0         0.0        NaN  
3               0.0         0.0         0.0        NaN  
4               0.0         0.0         0.0        NaN  
...             ...         ...         ...        ...  
5640997         0.0         0.0         0.0        NaN  
5640998         0.0         0.0         0.0        NaN  
5640999         0.0         0.0         0.0        NaN  
5641000         0.0         0.0         0.0        NaN  
5641001         0.0         0.0         0.0        NaN  

[5641002 rows x 14 columns]

In [5]:
big = big.dropna(axis=0, subset=['smalldata'])
big

toid        date  bigdata  \
1188999  osgb4000000031252081  2020/01/01       65   
1189000  osgb4000000031252081  2020/01/02       75   
1189001  osgb4000000031252081  2020/01/03       61   
1189002  osgb4000000031252081  2020/01/04       69   
1189003  osgb4000000031252081  2020/01/05       43   
...                       ...         ...      ...   
5470411  osgb4000000030147330  2021/12/27       35   
5470412  osgb4000000030147330  2021/12/28       53   
5470413  osgb4000000030147330  2021/12/29       45   
5470414  osgb4000000030147330  2021/12/30       33   
5470415  osgb4000000030147330  2021/12/31       36   

                                                  geometry    roadclassi  \
1188999  LINESTRING (528149 180507, 528153.7570000002 1...  Unclassified   
1189000  LINESTRING (528149 180507, 528153.7570000002 1...  Unclassified   
1189001  LINESTRING (528149 180507, 528153.7570000002 1...  Unclassified   
1189002  LINESTRING (528149 180507, 528153.7570000002 1...  Unclassified   
1189003  LINESTRING (528149 180507, 528153.7570000002 1...  Unclassified   
...                                                    ...           ...   
5470411  LINESTRING (529349 181634, 529354.8219999997 1...  Unclassified   
5470412  LINESTRING (529349 181634, 529354.8219999997 1...  Unclassified   
5470413  LINESTRING (529349 181634, 529354.8219999997 1...  Unclassified   
5470414  LINESTRING (529349 181634, 529354.8219999997 1...  Unclassified   
5470415  LINESTRING (529349 181634, 529354.8219999997 1...  Unclassified   

         length           formofway  trunkroad  primaryrou      directiona  \
1188999   34.79  Single Carriageway        0.0         0.0  bothDirections   
1189000   34.79  Single Carriageway        0.0         0.0  bothDirections   
1189001   34.79  Single Carriageway        0.0         0.0  bothDirections   
1189002   34.79  Single Carriageway        0.0         0.0  bothDirections   
1189003   34.79  Single Carriageway        0.0         0.0  bothDirections   
...         ...                 ...        ...         ...             ...   
5470411  218.91  Single Carriageway        0.0         0.0  bothDirections   
5470412  218.91  Single Carriageway        0.0         0.0  bothDirections   
5470413  218.91  Single Carriageway        0.0         0.0  bothDirections   
5470414  218.91  Single Carriageway        0.0         0.0  bothDirections   
5470415  218.91  Single Carriageway        0.0         0.0  bothDirections   

         startgrade  endgradese  elevationg  smalldata  
1188999         0.0         0.0         0.0    46332.0  
1189000         0.0         0.0         0.0    42984.0  
1189001         0.0         0.0         0.0    45048.0  
1189002         0.0         0.0         0.0    43758.0  
1189003         0.0         0.0         0.0    39098.0  
...             ...         ...         ...        ...  
5470411         0.0         0.0         0.3     1869.0  
5470412         0.0         0.0         0.3     1875.0  
5470413         0.0         0.0         0.3     2085.0  
5470414         0.0         0.0         0.3     1575.0  
5470415         0.0         0.0         0.3     1263.0  

[12393 rows x 14 columns]

In [6]:
for idx, row in big.iterrows():
    if row['roadclassi'] == 'ARoad':
        big.loc[idx, 'roadclassi'] = 0
    if row['roadclassi'] == 'BRoad':
        big.loc[idx, 'roadclassi'] = 1
    if row['roadclassi'] == 'LocalRoad':
        big.loc[idx, 'roadclassi'] = 2
    if row['roadclassi'] == 'Unclassified':
        big.loc[idx, 'roadclassi'] = 3

    if row['formofway'] == 'Single Carriageway':
        big.loc[idx, 'formofway'] = 0
    if row['formofway'] == 'Traffic Island Link At Junction':
        big.loc[idx, 'formofway'] = 1
    if row['formofway'] == 'Dual Carriageway':
        big.loc[idx, 'formofway'] = 2
    if row['formofway'] == 'Traffic Island Link':
        big.loc[idx, 'formofway'] = 3
    if row['formofway'] == 'Roundabout':
        big.loc[idx, 'formofway'] = 4
    if row['formofway'] == 'Slip Road':
        big.loc[idx, 'formofway'] = 5
    if row['formofway'] == 'Enclosed Traffic Area':
        big.loc[idx, 'formofway'] = 6
    if row['formofway'] == 'Shared Use Carriageway':
        big.loc[idx, 'formofway'] = 7

    if row['directiona'] == 'bothDirections':
        big.loc[idx, 'directiona'] = 0
    if row['directiona'] == 'inDirection':
        big.loc[idx, 'directiona'] = 1
    if row['directiona'] == 'inOppositeDirection':
        big.loc[idx, 'directiona'] = 2

big


F:\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


toid        date  bigdata  \
1188999  osgb4000000031252081  2020/01/01       65   
1189000  osgb4000000031252081  2020/01/02       75   
1189001  osgb4000000031252081  2020/01/03       61   
1189002  osgb4000000031252081  2020/01/04       69   
1189003  osgb4000000031252081  2020/01/05       43   
...                       ...         ...      ...   
5470411  osgb4000000030147330  2021/12/27       35   
5470412  osgb4000000030147330  2021/12/28       53   
5470413  osgb4000000030147330  2021/12/29       45   
5470414  osgb4000000030147330  2021/12/30       33   
5470415  osgb4000000030147330  2021/12/31       36   

                                                  geometry roadclassi  length  \
1188999  LINESTRING (528149 180507, 528153.7570000002 1...          3   34.79   
1189000  LINESTRING (528149 180507, 528153.7570000002 1...          3   34.79   
1189001  LINESTRING (528149 180507, 528153.7570000002 1...          3   34.79   
1189002  LINESTRING (528149 180507, 528153.7570000002 1...          3   34.79   
1189003  LINESTRING (528149 180507, 528153.7570000002 1...          3   34.79   
...                                                    ...        ...     ...   
5470411  LINESTRING (529349 181634, 529354.8219999997 1...          3  218.91   
5470412  LINESTRING (529349 181634, 529354.8219999997 1...          3  218.91   
5470413  LINESTRING (529349 181634, 529354.8219999997 1...          3  218.91   
5470414  LINESTRING (529349 181634, 529354.8219999997 1...          3  218.91   
5470415  LINESTRING (529349 181634, 529354.8219999997 1...          3  218.91   

        formofway  trunkroad  primaryrou directiona  startgrade  endgradese  \
1188999         0        0.0         0.0          0         0.0         0.0   
1189000         0        0.0         0.0          0         0.0         0.0   
1189001         0        0.0         0.0          0         0.0         0.0   
1189002         0        0.0         0.0          0         0.0         0.0   
1189003         0        0.0         0.0          0         0.0         0.0   
...           ...        ...         ...        ...         ...         ...   
5470411         0        0.0         0.0          0         0.0         0.0   
5470412         0        0.0         0.0          0         0.0         0.0   
5470413         0        0.0         0.0          0         0.0         0.0   
5470414         0        0.0         0.0          0         0.0         0.0   
5470415         0        0.0         0.0          0         0.0         0.0   

         elevationg  smalldata  
1188999         0.0    46332.0  
1189000         0.0    42984.0  
1189001         0.0    45048.0  
1189002         0.0    43758.0  
1189003         0.0    39098.0  
...             ...        ...  
5470411         0.3     1869.0  
5470412         0.3     1875.0  
5470413         0.3     2085.0  
5470414         0.3     1575.0  
5470415         0.3     1263.0  

[12393 rows x 14 columns]

In [7]:
# Output rows with non-NaN values in 'smalldata' columns
filtered_data = big[~big['smalldata'].isnull()]

# Output the value of the proposed column
columns_to_display = ['roadclassi', 'formofway', 'primaryrou', 'directiona', 'startgrade', 'endgradese','elevationg']
values_data = filtered_data[columns_to_display]
print(values_data)

# Output the count of these values
values_count = values_data.apply(lambda x: x.value_counts())
print(values_count)

        roadclassi formofway  primaryrou directiona  startgrade  endgradese  \
1188999          3         0         0.0          0         0.0         0.0   
1189000          3         0         0.0          0         0.0         0.0   
1189001          3         0         0.0          0         0.0         0.0   
1189002          3         0         0.0          0         0.0         0.0   
1189003          3         0         0.0          0         0.0         0.0   
...            ...       ...         ...        ...         ...         ...   
5470411          3         0         0.0          0         0.0         0.0   
5470412          3         0         0.0          0         0.0         0.0   
5470413          3         0         0.0          0         0.0         0.0   
5470414          3         0         0.0          0         0.0         0.0   
5470415          3         0         0.0          0         0.0         0.0   

         elevationg  
1188999         0.0  
1189000

In [8]:
# Feature Selection: roadclassi, formofway,  primaryrou,  directiona, elevationg 
df_list = big[['smalldata', 'bigdata', 'roadclassi']].values.tolist()
# df_list = big[['smalldata', 'bigdata']].values.tolist()
print(len(df_list))
# print(df_list)

12393


In [9]:
import numpy as np

arr = np.array(df_list).reshape(729, 17, -1)
print(arr.shape)
print(arr)

(729, 17, 3)
[[[4.6332e+04 6.5000e+01 3.0000e+00]
  [4.2984e+04 7.5000e+01 3.0000e+00]
  [4.5048e+04 6.1000e+01 3.0000e+00]
  ...
  [4.5813e+04 1.1500e+02 3.0000e+00]
  [5.1044e+04 1.0800e+02 3.0000e+00]
  [5.0565e+04 1.2800e+02 3.0000e+00]]

 [[4.5174e+04 8.9000e+01 3.0000e+00]
  [3.9785e+04 7.6000e+01 3.0000e+00]
  [4.5018e+04 1.1200e+02 3.0000e+00]
  ...
  [4.6068e+04 9.5000e+01 3.0000e+00]
  [4.0645e+04 1.1300e+02 3.0000e+00]
  [4.5261e+04 1.3100e+02 3.0000e+00]]

 [[4.6447e+04 1.3200e+02 3.0000e+00]
  [4.8438e+04 1.0900e+02 3.0000e+00]
  [4.8212e+04 1.3300e+02 3.0000e+00]
  ...
  [4.5176e+04 1.0900e+02 3.0000e+00]
  [4.4960e+04 1.5800e+02 3.0000e+00]
  [4.9584e+04 1.3000e+02 3.0000e+00]]

 ...

 [[1.0530e+03 4.4000e+01 3.0000e+00]
  [1.3000e+03 4.1000e+01 3.0000e+00]
  [1.3080e+03 4.7000e+01 3.0000e+00]
  ...
  [1.5800e+03 5.1000e+01 3.0000e+00]
  [1.7120e+03 3.6000e+01 3.0000e+00]
  [1.6120e+03 4.5000e+01 3.0000e+00]]

 [[1.4090e+03 3.2000e+01 3.0000e+00]
  [1.3280e+03 3.8000e+01

In [10]:
# Generate npz file
data = arr
np.savez('wes_net_0827/wes_net_0827/data/test17.npz', data=arr)

# Generate csv file

In [11]:
wes_net = gpd.read_file('wes_net_0827/data_preprocess/wes_net/wes_net.shp')

wes_net['id'] = wes_net['id'].astype(int)
# Convert to a DataFrame
wes = pd.DataFrame(wes_net)
#set it to display all columns
pd.set_option('display.max_columns', None)
wes

from      to      id  objectid                  toid  \
0        111     112      56      56.0  osgb4000000030407372   
1        191     192      96      96.0  osgb4000000030815020   
2        235     236     118     118.0  osgb4000000030135555   
3        253     254     127     127.0  osgb4000000030418885   
4        274     275     138     138.0  osgb5000005101647057   
...      ...     ...     ...       ...                   ...   
7733  103586  173413  289993  289961.0  osgb4000000030343580   
7734  112605  187233  289998  289966.0  osgb4000000030407389   
7735   76076  131805  290005  289973.0  osgb4000000030342684   
7736   20796  135139  290042  290010.0  osgb4000000030135672   
7737  128730  148632  290118  290086.0  osgb4000000031063610   

            identifier identifi_1  beginlifes  fictitious validfrom  \
0     4000000030407372       None  2017-04-15         0.0      None   
1     4000000030815020       None  2017-04-15         0.0      None   
2     4000000030135555       None  2017-04-15         0.0      None   
3     4000000030418885       None  2017-04-15         0.0      None   
4     5000005101647057       None  2017-04-15         0.0      None   
...                ...        ...         ...         ...       ...   
7733  4000000030343580       None  2017-04-15         0.0      None   
7734  4000000030407389       None  2017-04-15         0.0      None   
7735  4000000030342684       None  2017-04-15         0.0      None   
7736  4000000030135672       None  2017-04-15         0.0      None   
7737  4000000031063610       None  2017-04-15         0.0      None   

                            reasonforc    roadclassi  \
0     Modified Geometry And Attributes        B Road   
1     Modified Geometry And Attributes  Unclassified   
2     Modified Geometry And Attributes  Unclassified   
3     Modified Geometry And Attributes  Unclassified   
4     Modified Geometry And Attributes        A Road   
...                                ...           ...   
7733  Modified Geometry And Attributes  Unclassified   
7734  Modified Geometry And Attributes       Unknown   
7735  Modified Geometry And Attributes  Unclassified   
7736  Modified Geometry And Attributes  Unclassified   
7737  Modified Geometry And Attributes  Unclassified   

                            routehiera                        formofway  \
0                               B Road               Single Carriageway   
1                           Local Road               Single Carriageway   
2                           Local Road               Single Carriageway   
3                           Local Road               Single Carriageway   
4                       A Road Primary              Traffic Island Link   
...                                ...                              ...   
7733                        Local Road               Single Carriageway   
7734                        Local Road  Traffic Island Link At Junction   
7735                        Local Road               Single Carriageway   
7736                        Local Road               Single Carriageway   
7737  Restricted Secondary Access Road               Single Carriageway   

      trunkroad  primaryrou roadclas_1             roadname1 roadname2  \
0           0.0         0.0       B319         Chesham Place      None   
1           0.0         0.0       None  Westmoreland Terrace      None   
2           0.0         0.0       None          Marne Street      None   
3           0.0         0.0       None      Devonshire Close      None   
4           0.0        -1.0         A5          Edgware Road      None   
...         ...         ...        ...                   ...       ...   
7733        0.0         0.0       None       Marylebone Lane      None   
7734        0.0         0.0       None         Brompton Road      None   
7735        0.0         0.0       None  Abbey Orchard Street      None   
7736        0.0         0.0       None            Hall Place      None  

In [12]:
toid = big['toid'].unique()
toid_list = toid.tolist()
toid_list

['osgb4000000031252081',
 'osgb4000000030217372',
 'osgb4000000030146942',
 'osgb5000005153221184',
 'osgb4000000030237633',
 'osgb4000000030237923',
 'osgb4000000030239011',
 'osgb4000000031075354',
 'osgb4000000030216523',
 'osgb5000005151364365',
 'osgb4000000030099849',
 'osgb4000000030135721',
 'osgb5000005102006015',
 'osgb4000000030147277',
 'osgb4000000030146991',
 'osgb4000000030082291',
 'osgb4000000030147330']

In [13]:
# Filter wes by toid
small_wes = pd.DataFrame()
for item in toid_list:
    temp = wes.loc[wes['toid'] == item]
    small_wes = small_wes.append(temp)

small_wes

from      to      id  objectid                  toid  \
1631   92462   92463   59124   59119.0  osgb4000000031252081   
2044   41101  108935   73765   73758.0  osgb4000000030217372   
2782   17159  134040  101240  101232.0  osgb4000000030146942   
3156   67536  144443  114803  114793.0  osgb5000005153221184   
3232    9395   28550  118067  118057.0  osgb4000000030237633   
4208  170335  170336  154721  154710.0  osgb4000000030237923   
4211  130650  139445  154755  154744.0  osgb4000000030239011   
4799   50251  112474  179895  179883.0  osgb4000000031075354   
4987   72601  178085  188694  188678.0  osgb4000000030216523   
5440    4346  172995  226391  226369.0  osgb5000005151364365   
5442  211536  211537  226436  226414.0  osgb4000000030099849   
5677   17191   85370  239312  239287.0  osgb4000000030135721   
6111   32312  142212  253479  253452.0  osgb5000005102006015   
6322   71709  155630  258620  258592.0  osgb4000000030147277   
6508  211255  225695  262837  262809.0  osgb4000000030146991   
7128  193726  222250  275588  275559.0  osgb4000000030082291   
7502    4740   60531  282530  282500.0  osgb4000000030147330   

            identifier identifi_1  beginlifes  fictitious validfrom  \
1631  4000000031252081       None  2017-04-15         0.0      None   
2044  4000000030217372       None  2017-04-15         0.0      None   
2782  4000000030146942       None  2017-04-15         0.0      None   
3156  5000005153221184       None  2017-05-16         0.0      None   
3232  4000000030237633       None  2017-04-15         0.0      None   
4208  4000000030237923       None  2017-04-15         0.0      None   
4211  4000000030239011       None  2017-04-15         0.0      None   
4799  4000000031075354       None  2017-07-22         0.0      None   
4987  4000000030216523       None  2017-07-22         0.0      None   
5440  5000005151364365       None  2018-09-26         0.0      None   
5442  4000000030099849       None  2018-01-20         0.0      None   
5677  4000000030135721       None  2018-01-20         0.0      None   
6111  5000005102006015       None  2018-02-20         0.0      None   
6322  4000000030147277       None  2018-09-26         0.0      None   
6508  4000000030146991       None  2019-01-20         0.0      None   
7128  4000000030082291       None  2018-09-26         0.0      None   
7502  4000000030147330       None  2017-04-15         0.0      None   

                            reasonforc    roadclassi      routehiera  \
1631  Modified Geometry And Attributes  Unclassified      Local Road   
2044  Modified Geometry And Attributes        A Road          A Road   
2782  Modified Geometry And Attributes        A Road          A Road   
3156               Modified Attributes        A Road          A Road   
3232  Modified Geometry And Attributes        A Road          A Road   
4208  Modified Geometry And Attributes        A Road          A Road   
4211  Modified Geometry And Attributes        B Road          B Road   
4799                 Modified Geometry        A Road  A Road Primary   
4987                 Modified Geometry        A Road          A Road   
5440                 Modified Geometry        A Road          A Road   
5442               Modified Attributes        A Road          A Road   
5677               Modified Attributes        A Road  A Road Primary   
6111               Modified Attributes        A Road  A Road Primary   
6322                 Modified Geometry        A Road  A Road Primary   
6508               Modified Attributes        A Road          A Road   
7128                 Modified Geometry        A Road  A Road Primary   
7502  Modified Geometry And Attributes  Unclassified      Local Road   

               formofway  trunkroad  primaryrou roadclas_1  \
1631  Single Carriageway        0.0         0.0       None   
2044  Single Carriageway        0.0         0.0        A41   
2782    Dual Carriageway        0.0         0.0      A3212   
3156  Single Carriageway       

In [14]:
small_wes.rename(columns={'length': 'cost'}, inplace=True)
small_wes

from      to      id  objectid                  toid  \
1631   92462   92463   59124   59119.0  osgb4000000031252081   
2044   41101  108935   73765   73758.0  osgb4000000030217372   
2782   17159  134040  101240  101232.0  osgb4000000030146942   
3156   67536  144443  114803  114793.0  osgb5000005153221184   
3232    9395   28550  118067  118057.0  osgb4000000030237633   
4208  170335  170336  154721  154710.0  osgb4000000030237923   
4211  130650  139445  154755  154744.0  osgb4000000030239011   
4799   50251  112474  179895  179883.0  osgb4000000031075354   
4987   72601  178085  188694  188678.0  osgb4000000030216523   
5440    4346  172995  226391  226369.0  osgb5000005151364365   
5442  211536  211537  226436  226414.0  osgb4000000030099849   
5677   17191   85370  239312  239287.0  osgb4000000030135721   
6111   32312  142212  253479  253452.0  osgb5000005102006015   
6322   71709  155630  258620  258592.0  osgb4000000030147277   
6508  211255  225695  262837  262809.0  osgb4000000030146991   
7128  193726  222250  275588  275559.0  osgb4000000030082291   
7502    4740   60531  282530  282500.0  osgb4000000030147330   

            identifier identifi_1  beginlifes  fictitious validfrom  \
1631  4000000031252081       None  2017-04-15         0.0      None   
2044  4000000030217372       None  2017-04-15         0.0      None   
2782  4000000030146942       None  2017-04-15         0.0      None   
3156  5000005153221184       None  2017-05-16         0.0      None   
3232  4000000030237633       None  2017-04-15         0.0      None   
4208  4000000030237923       None  2017-04-15         0.0      None   
4211  4000000030239011       None  2017-04-15         0.0      None   
4799  4000000031075354       None  2017-07-22         0.0      None   
4987  4000000030216523       None  2017-07-22         0.0      None   
5440  5000005151364365       None  2018-09-26         0.0      None   
5442  4000000030099849       None  2018-01-20         0.0      None   
5677  4000000030135721       None  2018-01-20         0.0      None   
6111  5000005102006015       None  2018-02-20         0.0      None   
6322  4000000030147277       None  2018-09-26         0.0      None   
6508  4000000030146991       None  2019-01-20         0.0      None   
7128  4000000030082291       None  2018-09-26         0.0      None   
7502  4000000030147330       None  2017-04-15         0.0      None   

                            reasonforc    roadclassi      routehiera  \
1631  Modified Geometry And Attributes  Unclassified      Local Road   
2044  Modified Geometry And Attributes        A Road          A Road   
2782  Modified Geometry And Attributes        A Road          A Road   
3156               Modified Attributes        A Road          A Road   
3232  Modified Geometry And Attributes        A Road          A Road   
4208  Modified Geometry And Attributes        A Road          A Road   
4211  Modified Geometry And Attributes        B Road          B Road   
4799                 Modified Geometry        A Road  A Road Primary   
4987                 Modified Geometry        A Road          A Road   
5440                 Modified Geometry        A Road          A Road   
5442               Modified Attributes        A Road          A Road   
5677               Modified Attributes        A Road  A Road Primary   
6111               Modified Attributes        A Road  A Road Primary   
6322                 Modified Geometry        A Road  A Road Primary   
6508               Modified Attributes        A Road          A Road   
7128                 Modified Geometry        A Road  A Road Primary   
7502  Modified Geometry And Attributes  Unclassified      Local Road   

               formofway  trunkroad  primaryrou roadclas_1  \
1631  Single Carriageway        0.0         0.0       None   
2044  Single Carriageway        0.0         0.0        A41   
2782    Dual Carriageway        0.0         0.0      A3212   
3156  Single Carriageway       

In [15]:
small_wes = small_wes[['from', 'to', 'cost', 'geometry']]
small_wes

from      to    cost  \
1631   92462   92463   34.79   
2044   41101  108935   70.21   
2782   17159  134040  169.97   
3156   67536  144443   86.85   
3232    9395   28550   98.08   
4208  170335  170336  147.06   
4211  130650  139445   96.16   
4799   50251  112474  123.81   
4987   72601  178085   62.08   
5440    4346  172995  109.36   
5442  211536  211537  236.87   
5677   17191   85370   85.73   
6111   32312  142212  106.72   
6322   71709  155630  160.69   
6508  211255  225695  160.17   
7128  193726  222250  378.52   
7502    4740   60531  218.91   

                                               geometry  
1631  LINESTRING (528149.000 180507.000, 528153.757 ...  
2044  LINESTRING (527966.000 181831.000, 527975.000 ...  
2782  LINESTRING (530216.000 178622.000, 530186.000 ...  
3156  LINESTRING (528947.000 179343.000, 528954.768 ...  
3232  LINESTRING (528113.000 178752.000, 528179.827 ...  
4208  LINESTRING (529768.000 179396.000, 529892.617 ...  
4211  LINESTRING (528876.000 182020.000, 528865.000 ...  
4799  LINESTRING (529529.000 178612.000, 529566.913 ...  
4987  LINESTRING (527074.000 179697.000, 527071.000 ...  
5440  LINESTRING (529378.629 181305.822, 529373.713 ...  
5442  LINESTRING (530441.060 180377.643, 530451.000 ...  
5677  LINESTRING (526879.337 182649.637, 526831.000 ...  
6111  LINESTRING (526913.665 183064.802, 526980.549 ...  
6322  LINESTRING (527995.930 181981.113, 528063.197 ...  
6508  LINESTRING (528756.000 180077.000, 528770.000 ...  
7128  LINESTRING (528329.430 180216.248, 528317.000 ...  
7502  LINESTRING (529349.000 181634.000, 529354.822 ...

In [16]:
col_null = small_wes['cost'].isnull().sum(axis=0)
col_null

0

In [17]:
import math
def eucliDist(A, B):
    """Calculate the A,B Euclidean distance"""
    return math.sqrt(sum(np.power((A - B), 2)))

In [18]:
def getLength(item):
    """Calculate road distance"""
    euc_arr = []
    for i in range(0,len(item)-1):
        (x_from, y_from), (x_end, y_end) = item[i], item[i+1]
        A, B = np.array((x_from, y_from)), np.array((x_end, y_end))
        length = eucliDist(A, B)
        euc_arr.append(length)
    # print(sum(euc_arr))
    return sum(euc_arr)

In [19]:
from shapely.geometry import LineString
temp = []
cost = []
for idx, row in small_wes.iterrows():
    item = list(row['geometry'].coords)
    # Selecting the center as the route coordinates
    x_start, y_start = item[0]
    x_end, y_end = item[len(item)-1]
    x, y = (x_start + x_end)/2, (y_start + y_end)/2
    coordinate = (x, y)
    temp.append(coordinate)
    # Calculate route distance
    euclen = getLength(item)
    cost.append(euclen)


small_wes['coordinate'] = temp
small_wes['newcost'] = cost
small_wes

<ipython-input-19-d8da6f7e849a>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_wes['coordinate'] = temp
<ipython-input-19-d8da6f7e849a>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_wes['newcost'] = cost


from      to    cost  \
1631   92462   92463   34.79   
2044   41101  108935   70.21   
2782   17159  134040  169.97   
3156   67536  144443   86.85   
3232    9395   28550   98.08   
4208  170335  170336  147.06   
4211  130650  139445   96.16   
4799   50251  112474  123.81   
4987   72601  178085   62.08   
5440    4346  172995  109.36   
5442  211536  211537  236.87   
5677   17191   85370   85.73   
6111   32312  142212  106.72   
6322   71709  155630  160.69   
6508  211255  225695  160.17   
7128  193726  222250  378.52   
7502    4740   60531  218.91   

                                               geometry  \
1631  LINESTRING (528149.000 180507.000, 528153.757 ...   
2044  LINESTRING (527966.000 181831.000, 527975.000 ...   
2782  LINESTRING (530216.000 178622.000, 530186.000 ...   
3156  LINESTRING (528947.000 179343.000, 528954.768 ...   
3232  LINESTRING (528113.000 178752.000, 528179.827 ...   
4208  LINESTRING (529768.000 179396.000, 529892.617 ...   
4211  LINESTRING (528876.000 182020.000, 528865.000 ...   
4799  LINESTRING (529529.000 178612.000, 529566.913 ...   
4987  LINESTRING (527074.000 179697.000, 527071.000 ...   
5440  LINESTRING (529378.629 181305.822, 529373.713 ...   
5442  LINESTRING (530441.060 180377.643, 530451.000 ...   
5677  LINESTRING (526879.337 182649.637, 526831.000 ...   
6111  LINESTRING (526913.665 183064.802, 526980.549 ...   
6322  LINESTRING (527995.930 181981.113, 528063.197 ...   
6508  LINESTRING (528756.000 180077.000, 528770.000 ...   
7128  LINESTRING (528329.430 180216.248, 528317.000 ...   
7502  LINESTRING (529349.000 181634.000, 529354.822 ...   

                                   coordinate     newcost  
1631  (528165.5525000002, 180512.35505000036)   34.794357  
2044                     (527976.5, 181797.5)   70.215294  
2782                     (530179.0, 178545.5)  169.970578  
3156                     (528962.5, 179383.5)   86.846610  
3232  (528146.4134999998, 178787.90055000037)   98.087950  
4208  (529830.3084999998, 179435.04805000033)  147.065963  
4211                     (528862.0, 182066.0)   96.166560  
4799                     (529579.0, 178575.5)  123.811356  
4987                     (527043.0, 179695.5)   62.081863  
5440  (529324.9199999999, 181295.56955000013)  109.358965  
5442  (530503.0729999999, 180477.63349999953)  236.871583  
5677  (526846.0745000001, 182622.59355000034)   85.739813  
6111  (526947.1069999998, 183023.22204999998)  106.719438  
6322  (528072.4649999999, 182005.55649999995)  160.696786  
6508                     (528813.5, 180131.0)  160.169627  
7128  (528210.0959999999, 180363.08949999977)  378.528836  
7502                     (529393.0, 181534.0)  218.915050

In [20]:
small_wes = small_wes[['from', 'to', 'newcost', 'coordinate']]
small_wes

from      to     newcost                               coordinate
1631   92462   92463   34.794357  (528165.5525000002, 180512.35505000036)
2044   41101  108935   70.215294                     (527976.5, 181797.5)
2782   17159  134040  169.970578                     (530179.0, 178545.5)
3156   67536  144443   86.846610                     (528962.5, 179383.5)
3232    9395   28550   98.087950  (528146.4134999998, 178787.90055000037)
4208  170335  170336  147.065963  (529830.3084999998, 179435.04805000033)
4211  130650  139445   96.166560                     (528862.0, 182066.0)
4799   50251  112474  123.811356                     (529579.0, 178575.5)
4987   72601  178085   62.081863                     (527043.0, 179695.5)
5440    4346  172995  109.358965  (529324.9199999999, 181295.56955000013)
5442  211536  211537  236.871583  (530503.0729999999, 180477.63349999953)
5677   17191   85370   85.739813  (526846.0745000001, 182622.59355000034)
6111   32312  142212  106.719438  (526947.1069999998, 183023.22204999998)
6322   71709  155630  160.696786  (528072.4649999999, 182005.55649999995)
6508  211255  225695  160.169627                     (528813.5, 180131.0)
7128  193726  222250  378.528836  (528210.0959999999, 180363.08949999977)
7502    4740   60531  218.915050                     (529393.0, 181534.0)

In [21]:
small_wes = small_wes.reset_index(drop=True)
small_wes

from      to     newcost                               coordinate
0    92462   92463   34.794357  (528165.5525000002, 180512.35505000036)
1    41101  108935   70.215294                     (527976.5, 181797.5)
2    17159  134040  169.970578                     (530179.0, 178545.5)
3    67536  144443   86.846610                     (528962.5, 179383.5)
4     9395   28550   98.087950  (528146.4134999998, 178787.90055000037)
5   170335  170336  147.065963  (529830.3084999998, 179435.04805000033)
6   130650  139445   96.166560                     (528862.0, 182066.0)
7    50251  112474  123.811356                     (529579.0, 178575.5)
8    72601  178085   62.081863                     (527043.0, 179695.5)
9     4346  172995  109.358965  (529324.9199999999, 181295.56955000013)
10  211536  211537  236.871583  (530503.0729999999, 180477.63349999953)
11   17191   85370   85.739813  (526846.0745000001, 182622.59355000034)
12   32312  142212  106.719438  (526947.1069999998, 183023.22204999998)
13   71709  155630  160.696786  (528072.4649999999, 182005.55649999995)
14  211255  225695  160.169627                     (528813.5, 180131.0)
15  193726  222250  378.528836  (528210.0959999999, 180363.08949999977)
16    4740   60531  218.915050                     (529393.0, 181534.0)

In [22]:
coord_list = list(small_wes['coordinate'])
# eucdist_list = list(small_wes['newcost'])

from_list = []
to_list = []
eucdist_list = []
euc_distance_list = []
for idx_i, i in enumerate(coord_list):
    for idx_j, j in enumerate(coord_list):
        if idx_i < idx_j:
            euc_distance = eucliDist(np.array(i),np.array(j))
            euc_distance_list.append(euc_distance)
            if euc_distance <= 2000:
                # print(f'{idx_i}->{idx_j}:',euc_distance)
                from_list.append(idx_i)
                to_list.append(idx_j)
                eucdist_list.append(euc_distance) 
euc_distance_mean = np.mean(euc_distance_list)
euc_distance_median = np.median(euc_distance_list)
print("The median of 'euc_distance' is:", euc_distance_median)
print("The average of 'euc_distance' is:", euc_distance_mean)
# percentile
q1 = np.percentile(euc_distance_list, 25)
q3 = np.percentile(euc_distance_list, 75)
print("The first quartile of 'euc_distance' is:", q1)
print("The third quartile of 'euc_distance' is:", q3)
# min and max 
euc_distance_max = np.max(euc_distance_list)
euc_distance_min = np.min(euc_distance_list)
print("The maximum of 'euc_distance' is:", euc_distance_max)
print("The minimum of 'euc_distance' is:", euc_distance_min)

new_wes = pd.DataFrame()
new_wes['from'] = from_list
new_wes['to'] = to_list
new_wes['cost'] = eucdist_list
new_wes

The median of 'euc_distance' is: 2103.5892735493817
The average of 'euc_distance' is: 2290.258867257511
The first quartile of 'euc_distance' is: 1446.3849013991314
The third quartile of 'euc_distance' is: 2940.5678341430953
The maximum of 'euc_distance' is: 5522.239321190821
The minimum of 'euc_distance' is: 155.7701120536318


from  to         cost
0      0   1  1298.975901
1      0   3  1381.824534
2      0   4  1724.560705
3      0   5  1982.927863
4      0   6  1702.601466
..   ...  ..          ...
59    13  15  1648.223328
60    13  16  1402.204771
61    14  15   646.499747
62    14  16  1517.968791
63    15  16  1664.419800

[64 rows x 3 columns]

In [41]:
new_wes.to_csv("wes_net_0827/wes_net_0827/data/test17.csv", index=False, sep=',')

In [ ]:
# # arrange in order
# from_arr = small_wes['from'].values.tolist()
# to_arr = small_wes['to'].values.tolist()
# arr = from_arr + to_arr
# # print(from_arr)
# arr1 = list(set(arr))
# arr2 = sorted(arr1, reverse=False)
#
# from_dict = dict(enumerate(arr2))
# print(from_dict)

In [ ]:
# new_dict = dict(zip(from_dict.values(), from_dict.keys()))
# print(new_dict)

In [ ]:
# df = pd.read_csv('test17.csv')
# df

In [ ]:
# for idx in df.index:
#     df.loc[idx, 'from'] = new_dict[df.loc[idx, 'from']]
#     df.loc[idx, 'to'] = new_dict[df.loc[idx, 'to']]
# df

In [ ]:
# df.to_csv("test17.csv", index=False, sep=',')